### PR TITLE
add alternative impl

### PR DESCRIPTION
**Pull request by fennewald**
Your video was very interesting!

I've been doing rust professionally for a few years, and wanted to try my hand at an implementation.

Besides some general usage of `std::ops` to clean up code reading, the only interesting change is instead of two loops over all entities, I do one loop over all and the second loop over only entities to the right.

Additionally, I created a single entity struct. In this case, I don't think SOA is useful.

I'm curious what performance differences you see on your hardware! I didn't know which values to use to test, but I'm seeing roughly at 4x speedup on my hardware

### CODE REVIEW

**Comment by unitoftime** [comment]
Hey! Very cool! I really appreciate you taking the time to write this up. I'm seeing lots of rust features that I didn't know about, which is cool to learn. I'll hopefully have some time tomorrow to try out your alternative implementation.

You definitely correctly picked out the scalability problem by optimizing the O(n^2) loop. I didn't really talk about it in the video, but one of my goals was to keep the algorithmic implementation of Rust and Go as similar as possible. Admittedly, I picked the O(n^2) implementation because it was simpler to write.

There's some other cool optimizations you can do in collision detection, such as quadtrees (KD trees), and spatial hashes.

Yeah you're probably right about the SOA not being useful here, because all the data is needed in the n^2 loop, it's already relatively "tightly packed". In some cases I got performance decreases by splitting up the data too much (I think I called that one `native-split` or something. Still interesting to see!

**Comment by fennewald** [comment]
I'll add back in the double loop then in the name of sportsmanship, but it does highlight an interesting benefit of SOA.

Without SOA, the collision loop requires multiple mutable borrows into the entities vector. You can use split_at_mut to do this safely, but if you don't know which index is smaller (i or j), it becomes difficult to write it in an efficient way. My approach is to use `unsafe` which may hinder the compilers ability to optimize things, with the additional negative of being ugly.

**Comment by unitoftime** [comment]
Haha I appreciate the sportsmanship :)

Ah interesting. I didn't even think of that. When writing my SOA based loops I did have to be somewhat conscious of which values needed to be mutable and which didn't.

I guess my Go biases leaked in more than I thought!

Anyways, I appreciate the contribution and learnings!

**Comment by unitoftime** [comment]
Just built and tested your code on my computer.
I did a test with 10k entities and 0 for collision limit (effectively infinite health, which is required for the more basic non-deletion cases).

On my hardware your `other` mode ran `0.001` ms faster per iteration (compared to `native`). Very cool! A nice little improvement!

I'll pull your change in but I'm going to rename the program mode to `fennewald` if that's okay.

Thanks!

**Pull request merged**
